use super::docs_layout::DocsLayout;
use super::product::NativeScreen;
use leptos::prelude::*;
use leptos_meta::Title;

#[component]
pub fn MenuBarGuidePage() -> impl IntoView {
    view! {
        <Title text="Menu bar and Settings — term-web"/>
        <DocsLayout active="menu">
            <p class="eyebrow">"MENU BAR & SETTINGS"</p><h1>"Find it. Understand it."<br/>"Then decide."</h1>
            <p class="doc-lead">"The menu puts your running servers next to the context you need to choose what to open, keep, or stop."</p>
            <section id="read"><h2>"Read a server row"</h2><NativeScreen src="menu-bar.png" label="ACTUAL MENU / SAMPLE PROJECTS" description="Three servers with projects, agent attribution, HTTP status, and a checkout collision." width=800 height=712/>
                <dl class="doc-definitions"><div><dt>"Port and URL"</dt><dd>"The address to open. TLS-only servers use HTTPS when detected."</dd></div><div><dt>"Project, branch, and worktree"</dt><dd>"The server’s working folder and its git context. Hover over the project name for the full path."</dd></div><div><dt>"Agent and orphan label"</dt><dd>"Who appears to have launched it. Orange attribution marks a server whose known launcher has ended or whose launcher PID has been reused."</dd></div><div><dt>"Status and page title"</dt><dd>"A short loopback HTTP check. A 404 still means the server answered; it does not mean the project is broken or disposable."</dd></div><div><dt>"Process, PID, and uptime"</dt><dd>"The process behind the listener and how long it has been running. Uptime alone is not a reason to stop it."</dd></div></dl>
            </section>
            <section id="actions"><h2>"Go straight to the right place"</h2><ul><li><strong>"Open"</strong>" opens the server in your default browser."</li><li><strong>"Copy URL"</strong>" gives you its address."</li><li><strong>"Reveal"</strong>" shows the project folder in Finder."</li><li><strong>"Terminal"</strong>" opens the project folder in your chosen terminal."</li><li><strong>"Stop"</strong>" starts a confirmation for that server."</li></ul></section>
            <section id="stop"><h2>"Stop a server you no longer need"</h2><ol class="doc-steps"><li>"Check the project, port, and process first. An orphaned server may still be a preview you want to keep."</li><li>"Choose Stop, then confirm. The app sends SIGTERM to one verified server process, giving it a chance to exit cleanly."</li><li>"If that same process remains after about three seconds, the menu offers a separate force-kill confirmation. SIGKILL gives the process no cleanup opportunity."</li><li>"Read the refreshed list. A watcher can start a replacement server; a new process on the old port is a new decision."</li></ol><p>"Identity checks use the PID, process name, and start time. A reused PID or an unverifiable process is not signalled. Protected system, daemon, app-helper, other-user, and term-web processes cannot be stopped. Signals never target a whole process group."</p><NativeScreen src="stop-confirmation.png" label="ACTUAL STOP CONFIRMATION / SAMPLE PROJECTS" description="The confirmation appears before a signal is sent." width=800 height=800/></section>
            <section id="settings"><h2>"Make the list work for you"</h2><dl class="doc-definitions"><div><dt>"Refresh every"</dt><dd>"Choose 2, 3, 5, 10, or 30 seconds. The default is 5; opening the menu also refreshes it."</dd></div><div><dt>"Show hidden servers"</dt><dd>"See an extra section with each hidden listener and its reason. Find a missing server before changing rules."</dd></div><div><dt>"Check HTTP status and page title"</dt><dd>"Enable or disable GET requests to your local servers while the menu is open."</dd></div><div><dt>"Open folders in"</dt><dd>"Choose iTerm2, Ghostty, Warp, or Terminal when installed. Automatic prefers them in that order."</dd></div><div><dt>"Launch at login"</dt><dd>"Register an installed /Applications copy and approve it in Login Items if macOS asks."</dd></div></dl></section>
            <section id="ignore"><h2>"Hide the noise"</h2><p>"Settings → Ignore List controls structural hide rules, process names, and ports. Names match exactly without case sensitivity; a trailing * matches a prefix. Reset to Defaults restores the built-in list."</p><p>"System executables, background daemons, app helpers, and common database or broker ports are hidden by default. Interpreters such as node, bun, python, and ruby are exempt from structural and port rules. An explicit process-name rule can still hide them."</p><p>"The CLI and MCP server share the saved list. Showing a protected listener changes visibility only; it never enables Stop."</p><a class="text-link" href="/docs/troubleshooting#missing">"If a server is still missing →"</a></section>
        </DocsLayout>
    }
}
