use super::docs_layout::DocsLayout;
use super::product::CodeBlock;
use leptos::prelude::*;
use leptos_meta::Title;

#[component]
pub fn TroubleshootingPage() -> impl IntoView {
    view! {
        <Title text="Troubleshooting — term-web"/>
        <DocsLayout active="help">
            <p class="eyebrow">"TROUBLESHOOTING"</p><h1>"A little more context."</h1>
            <p class="doc-lead">"Start with what the list actually shows. Hidden, unknown, not ready, and refused each mean something different."</p>
            <section id="missing"><h2>"A server is missing"</h2><p>"Open Settings → General → Show hidden servers, or run list --all. A hidden row includes its hide reason. Adjust the corresponding Ignore List rule if you want it in the normal list."</p><CodeBlock label="Include hidden listeners" code="term-web list --all --no-probe"/><p>"term-web sees TCP listeners owned by your user on this Mac. A stopped process, a different user’s process, or a service only listening on a remote machine will not appear. A container’s internal process may not be visible as your Mac’s server; the detector does not inspect inside containers."</p></section>
            <section id="agent"><h2>"There’s no agent name or orphan label"</h2><p>"A server launched from your own shell can correctly have no agent. An agent’s identity needs its markers in the environment or a recognizable live ancestor. Launcher liveness needs a known launcher PID; missing information stays unknown."</p><p>"--mine and MCP mine=true require recognized Claude Code caller markers. A generic terminal or Codex-only connection does not automatically provide them."</p><a class="text-link" href="/docs/agents#attribution">"Attribution and ownership →"</a></section>
            <section id="response"><h2>"HTTP shows a timeout, 404, or 500"</h2><p>"A timeout can mean the server is still starting or did not answer the short probe. Let the next refresh try again. A 404 or 500 is an actual response; open the URL to inspect your app. wait succeeds for any HTTP response and is not an application health test."</p><p>"For a non-HTTP service, use wait --listen-only. To avoid GET requests entirely, disable status checks in Settings and use list --no-probe for the CLI."</p></section>
            <section id="stop"><h2>"Stop is refused or the server comes back"</h2><p>"Read the message. Protected listeners are never stoppable, even when you show them. A missing start time, reused PID, or failed identity check also prevents a signal. If unrelated processes share the port, the CLI needs --pid and MCP needs pid."</p><p>"MCP’s default Stop needs caller ownership. Ask the user before any_owner; do not treat an ownership error as permission to retry broadly."</p><p>"If the original process survives SIGTERM, the app offers force kill for that exact process. A watcher or supervisor may start a replacement. Refresh and identify it; the old confirmation does not apply to the replacement."</p></section>
            <section id="command"><h2>"Command not found or MCP won’t connect"</h2><p>"The source build’s CLI is .build/debug/term-web. An installed package puts its link at /usr/local/bin/term-web; your terminal or agent needs that directory on its PATH. An installed app also carries the executable here:"</p><CodeBlock label="Check an installed copy" code="/Applications/term-web.app/Contents/MacOS/term-web version\n/Applications/term-web.app/Contents/MacOS/term-web help"/><p>"Use the verified absolute executable path in your MCP client configuration if necessary. A stdio MCP process waits for client requests; starting term-web mcp manually is not the ordinary inventory command."</p></section>
            <section id="login"><h2>"Launch at login or Settings isn’t behaving"</h2><p>"Enable Launch at login from /Applications/term-web.app. Check System Settings → General → Login Items if approval is needed. A development copy registered from build/ points to that temporary path."</p><p>"If Settings opens behind other windows, click the menu bar icon again or bring the Settings window forward in Mission Control. After an upgrade, Quit and reopen the app to load the new binary."</p></section>
            <section id="limits"><h2>"Detection limits"</h2><ul><li>"Framework labels are guesses from process details, nearby manifests, and response headers."</li><li>"macOS folder-access denial can make project classification less specific."</li><li>"Agent attribution and orphan detection depend on available evidence."</li><li>"Collision detection observes checkouts, not intended file writes or locks."</li><li>"Separate Codex desktop chats sharing one app server look like one session."</li><li>"A local HTTP response does not establish app correctness or remote deployment."</li></ul><a class="text-link" href="/privacy">"Privacy and local permissions →"</a></section>
            <section id="report"><h2>"Make a useful problem report"</h2><p>"Record your term-web version, macOS version, the action you took, and the exact message. Note whether Show hidden servers changes the result. Review screenshots and JSON before sharing: they can include project paths, branch names, ports, and session IDs."</p><p>"There is no in-app report upload or support form. The app does not send diagnostics on your behalf."</p></section>
        </DocsLayout>
    }
}
