use super::docs_layout::DocsLayout;
use super::product::CodeBlock;
use leptos::prelude::*;
use leptos_meta::Title;

#[component]
pub fn CliGuidePage() -> impl IntoView {
    view! {
        <Title text="Command line — Still Here"/>
        <DocsLayout active="cli">
            <p class="eyebrow">"COMMAND LINE"</p><h1>"The same clarity."<br/>"One command away."</h1>
            <p class="doc-lead">"Use tables to find your bearings, JSON for scripts, and explicit commands to open, wait for, or stop a server."</p>
            <nav class="document-nav" aria-label="Command reference"><a href="#list" target="_self">"List"</a><a href="#sessions" target="_self">"Sessions"</a><a href="#wait" target="_self">"Wait"</a><a href="#open" target="_self">"Open"</a><a href="#stop" target="_self">"Stop"</a><a href="#json" target="_self">"JSON"</a></nav>
            <section id="path"><h2>"Find the command"</h2><p>"Examples assume stillhere is on your PATH. A source build places it at .build/debug/stillhere. The intended installer links /usr/local/bin/stillhere to the CLI inside the app."</p><CodeBlock label="Help and version" code="stillhere version\nstillhere help\nstillhere help stop"/><a class="text-link" href="/docs/troubleshooting#command">"Command not found? →"</a></section>
            <section id="list"><h2>"List what’s running"</h2><CodeBlock label="List syntax" code="stillhere [list] [--json] [--all] [--mine] [--orphans] [--no-probe]"/><dl class="doc-definitions"><div><dt>"--json"</dt><dd>"Stable keys, null for unknown values, and ISO 8601 dates."</dd></div><div><dt>"--all"</dt><dd>"Include listeners hidden by your ignore rules."</dd></div><div><dt>"--mine"</dt><dd>"Limit results to the calling Claude Code session. It needs inherited session markers and fails outside a recognized caller."</dd></div><div><dt>"--orphans"</dt><dd>"Show servers whose known launching session has ended."</dd></div><div><dt>"--no-probe"</dt><dd>"Skip the HTTP status and page-title check."</dd></div></dl><CodeBlock label="Inspect a busy machine" code="stillhere\nstillhere list --orphans\nstillhere list --all --no-probe"/></section>
            <section id="sessions"><h2>"Inspect agent sessions"</h2><CodeBlock label="Session syntax" code="stillhere sessions [--json] [--all] [--check]"/><p>"See agents, PIDs, checkouts, branches, related servers, and collisions between independent writers. --all includes sessions with no detected checkout. --check prints a collision note for a Claude Code SessionStart hook and always exits 0."</p><a class="text-link" href="/docs/agents#collisions">"Collision detection and its limits →"</a></section>
            <section id="wait"><h2>"Wait for a real response"</h2><CodeBlock label="Wait syntax" code="stillhere wait <port> [--timeout SECONDS] [--listen-only] [--json]"/><p>"The default timeout is 30 seconds. Success prints the URL. --listen-only waits for a socket without requiring HTTP; use it for a non-HTTP service."</p><CodeBlock label="Open after the listener answers" code="stillhere wait 5173 --timeout 60 && stillhere open 5173"/><p>"Any HTTP status counts, including 404 and 500. Ready means listening and answering, not passing an app health check. A timeout exits 1; an in-flight probe may finish shortly after the deadline."</p></section>
            <section id="open"><h2>"Open the preview"</h2><CodeBlock label="Open syntax" code="stillhere open <port>"/><p>"Open the server in your default browser. A probe selects HTTPS for TLS-only servers. Hidden listeners count when you name a port explicitly. If unrelated processes share a port, inspect the list before choosing what to do."</p></section>
            <section id="stop"><h2>"Stop the identified process"</h2><CodeBlock label="Stop syntax" code="stillhere stop <port> [--pid PID] [--yes] [--force]\nstillhere stop --orphans [--yes] [--force]"/><p>"Stop asks for confirmation, sends SIGTERM, and waits for exit. --yes skips the prompt and is required without a terminal to ask on. --pid chooses a process when unrelated listeners share a port; without it, an ambiguous stop is refused."</p><p>"--force still tries SIGTERM first. If the same verified process remains, it sends SIGKILL. Protected processes remain protected with every flag."</p><CodeBlock label="Review, then choose" code="stillhere list --orphans\nstillhere stop 5173"/><p>"For deliberate batch cleanup, stop --orphans asks before signalling the selected orphaned servers. Orphaned describes launcher liveness, not permission to discard a server. In a script, add --yes only when you intend to skip confirmation."</p><a class="text-link" href="/docs/menu-bar#stop">"Identity checks and force-kill behavior →"</a></section>
            <section id="json"><h2>"Read JSON without guessing"</h2><p>"A list response is an array of server reports. Keys are port, url, pid, process, framework, project, git, agent, http, startedAt, uptimeSeconds, hidden, and stoppable. Every key is present; unavailable information is null."</p><p>"Agent data includes attribution evidence, optional session and launcher identity, launcher liveness, and orphaned. HTTP data includes status, title, error, and latencyMilliseconds. hidden explains visibility; stoppable describes eligibility for a stop attempt."</p><p>"wait --json returns ready, waitedMilliseconds, and server. sessions --json returns sessions and collisions. Reports include project paths and optional session IDs; they omit raw command lines and process environments."</p><CodeBlock label="Machine-readable inventory" code="stillhere list --json\nstillhere sessions --json\nstillhere wait 5173 --json"/></section>
            <section id="exit"><h2>"Exit codes"</h2><div class="doc-table"><table><caption>"CLI results"</caption><thead><tr><th scope="col">"Code"</th><th scope="col">"Meaning"</th></tr></thead><tbody><tr><th scope="row">"0"</th><td>"Success. Empty lists are successful; sessions --check always returns 0."</td></tr><tr><th scope="row">"1"</th><td>"Failure, refused or cancelled stop, no matching stop target, or wait timeout."</td></tr><tr><th scope="row">"2"</th><td>"Usage error, such as an unknown flag or invalid port."</td></tr></tbody></table></div><p>"Ports can be written as 5173 or :5173 and must be in the range 1–65535. Check stillhere help for the version you actually run."</p></section>
        </DocsLayout>
    }
}
